#line 2 "lex.yy.cpp"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yytext_ptr -= yy_more_len; \
	yyleng = (int) (yy_cp - yytext_ptr); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 69
#define YY_END_OF_BUFFER 70
static yyconst short int yy_accept[260] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   25,   25,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   70,   68,   42,   61,
       11,   61,   68,   61,   68,   61,   61,   67,   61,   61,
       61,   39,   61,   68,   61,   61,   68,   68,    8,    9,
        8,    5,    6,   16,   14,   15,   16,   69,   28,   27,
       28,   28,   23,   22,   25,   26,   24,   28,   28,   68,
       68,   68,   68,   19,    2,   51,   40,   55,    0,    0,
        0,    0,    0,   60,    7,    4,   67,   43,   47,   50,
       49,   48,   45,   39,   58,   41,   54,   59,   57,   56,

        0,    0,   41,   41,   41,   41,   10,   13,   12,    0,
        0,    0,    0,   22,   25,   24,    0,    0,    0,    0,
        0,   41,    0,    0,   41,    2,   53,    0,   64,    0,
       62,   63,    0,   66,    0,   65,    0,    0,   44,   52,
       46,   41,    0,    0,    0,   41,   41,   41,   41,   41,
        0,    0,    0,    0,    0,   41,   41,    0,   41,   62,
       63,    0,    0,    0,    0,    0,   41,   41,   41,   41,
       41,   41,    0,    0,    0,    0,    0,    0,    0,   41,
       41,    0,   41,    0,    0,    0,    0,    0,    0,   41,
       41,   41,   41,   41,   41,   31,    0,    0,    0,    0,

        0,    0,   33,   41,   41,    0,   34,    0,    0,    0,
        0,    0,    0,   41,   20,   41,   41,   41,   18,   35,
       32,   29,    0,   33,    0,   35,   36,   34,    0,    0,
        0,   20,    0,   18,   17,   20,   21,   41,   41,   35,
       30,   36,   35,    0,    1,   17,   21,   21,   38,   41,
        3,   38,   38,   38,   41,   37,   37,   37,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    3,    4,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    5,    6,    7,    8,    7,    9,   10,    7,
        7,   11,    7,    7,   12,    7,   13,   14,   14,   15,
       15,   15,   15,   15,   15,   16,   16,    7,    7,   17,
       18,   19,   20,    7,   21,   22,   21,   23,   21,   21,
       24,   25,   24,   24,   24,   24,   24,   24,   26,   24,
       24,   24,   27,   24,   24,   24,   24,   28,   24,   28,
        7,   29,    7,   30,   31,   32,   33,   22,   34,   35,

       36,   37,   24,   38,   39,   24,   24,   40,   41,   42,
       43,   24,   24,   24,   44,   45,   46,   24,   47,   28,
       24,   28,    7,   48,    7,   49,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[50] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    4,    1,    1,
        1,    1,    1,    5,    5,    5,    1,    1,    1,    2,
        6,    6,    6,    7,    7,    7,    7,    6,    1,    1,
        6,    1,    6,    6,    6,    6,    6,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    1,    1
    } ;

static yyconst short int yy_base[276] =
    {   0,
        0,   48,   48,   49,  767,  766,   50,   57,    0,    0,
      765,   62,   94,    0,  143,    0,  764,  191,    0,   55,
        0,  194,  763,  196,  208,    0,  766,  772,  772,  747,
      772,  772,    0,  755,  234,  744,   56,   57,   57,   58,
       63,    0,  713,    0,  713,  192,  205,  167,  772,  772,
      747,  772,  772,  772,  772,  772,   49,  772,  772,  772,
      260,   53,  772,    0,    0,  772,  292,  264,   54,  340,
      175,  342,  723,  772,    0,  740,    0,  772,  345,  347,
      754,  363,  248,  772,  772,  174,  337,  739,  772,  737,
      772,  772,  735,    0,  772,    0,  772,  772,  772,  772,

      352,  229,  717,  182,  713,  709,  772,  772,  772,  354,
      240,   28,  713,    0,    0,    0,  367,  245,   43,  377,
      346,  163,  385,  354,  175,    0,  772,  392,  382,  411,
      414,  718,  745,  744,  404,  422,  703,  703,  772,  772,
      772,    0,  708,  706,  700,  704,   49,  706,  698,  703,
      693,  701,  223,  691,  185,  690,  698,  240,  688,  432,
      700,  683,  696,  691,  329,  692,  687,  689,  689,  683,
      686,  685,  249,  681,  683,  683,  678,  672,  680,  251,
      675,  669,  310,  674,  670,  671,  673,  673,  671,  664,
      668,  668,  657,  658,  664,  772,  659,  652,  645,  637,

      362,  633,    0,  625,  528,  369,    0,  477,  431,  420,
      424,  424,  422,  422,  401,  420,  421,  415,    0,    0,
      772,  772,  401,  772,  374,  463,    0,  772,  357,  342,
      322,  413,  310,  772,    0,  419,  431,  253,  205,    0,
      772,  772,    0,  180,  772,  772,  438,  441,  512,  164,
      772,    0,  449,  452,   26,  561,    0,    0,  772,  610,
      617,  624,  631,  638,  642,  646,  648,  652,  659,  663,
      669,  672,  679,  686,  693
    } ;

static yyconst short int yy_def[276] =
    {   0,
      259,    1,  260,  260,  261,  261,  262,  262,  263,  263,
      264,  264,  259,   13,  259,   15,  264,  264,    1,    1,
        1,    1,    1,    1,  263,   25,  259,  259,  259,  259,
      259,  259,  265,  259,  259,  259,  259,  259,  259,  259,
      259,  266,  259,  267,  259,  259,  259,  267,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  268,  269,  259,  259,  259,  259,  259,
      267,  259,   71,  259,  270,  259,  265,  259,  259,  259,
      271,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  266,  259,  272,  259,  259,  259,  259,

      259,  259,  272,  272,  272,  272,  259,  259,  259,  259,
      259,  259,  259,  268,  269,   67,  259,  259,  259,  259,
      259,  272,  259,  259,  272,  270,  259,  259,  259,  259,
      259,  259,  271,  271,  259,  259,  259,  259,  259,  259,
      259,  272,  259,  259,  259,  272,  272,  272,  272,  272,
      259,  259,  259,  259,  259,  272,  272,  259,  272,  259,
      259,  259,  259,  259,  259,  259,  272,  272,  272,  272,
      272,  272,  259,  259,  259,  259,  259,  259,  259,  272,
      272,  259,  272,  259,  259,  259,  259,  259,  259,  272,
      272,  272,  272,  272,  272,  259,  259,  259,  259,  259,

      259,  259,  272,  272,  272,  259,  272,  259,  259,  259,
      259,  259,  259,  272,  272,  272,  272,  272,  272,  273,
      259,  259,  259,  259,  259,  259,  272,  259,  259,  259,
      259,  259,  259,  259,  272,  259,  272,  272,  272,  273,
      259,  259,  226,  259,  259,  259,  259,  259,  259,  272,
      259,  274,  274,  249,  272,  259,  275,  256,    0,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259
    } ;

static yyconst short int yy_nxt[822] =
    {   0,
       28,   28,   28,   29,   30,   31,   32,   33,   34,   35,
       32,   36,   37,   38,   38,   38,   39,   40,   41,   32,
       42,   42,   42,   42,   42,   42,   42,   42,   28,   43,
       42,   44,   42,   42,   42,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   42,   45,   46,   47,
       47,   50,   50,   55,  108,   56,   70,   70,   51,   51,
       55,  256,   56,   61,   61,   60,   85,  151,   86,  152,
       87,   87,   87,   88,   89,   90,   91,  109,   57,   48,
       92,   93,  154,  168,  152,   57,   71,   87,  112,  119,
      169,  113,  113,   62,   58,   58,   58,   63,   58,   58,

       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   64,   64,   64,   64,   64,   64,
       64,   64,   58,   58,   64,   58,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   58,   58,   65,   65,   65,   66,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   67,   67,   67,   67,   67,   67,   67,
       67,   65,   65,   67,   65,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       65,   65,   68,   68,   60,   72,   72,   47,   47,   74,

       98,  103,  156,  255,  157,  104,  101,  101,  137,  103,
      122,  105,  106,  104,  159,  251,  157,  138,  147,  105,
      106,   99,   69,  148,  178,   73,  179,   48,   75,   75,
       75,   75,   75,   75,   75,   75,  102,  250,   75,  100,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   79,   80,  175,   81,   82,
       83,  110,  110,  143,  176,  117,  117,  144,   80,   79,
       80,   81,   81,   82,  145,  112,   82,   83,  113,  182,
      119,  179,   80,  113,  196,   81,  203,  197,  249,  204,
       82,  111,  115,  115,  115,  118,  115,  115,  115,  116,

      115,  115,  115,  115,  115,  116,  116,  116,  115,  115,
      115,  115,  116,  116,  116,  116,  116,  116,  116,  116,
      115,  115,  116,  115,  116,  116,  116,  116,  116,  116,
      116,  116,  116,  116,  116,  116,  116,  116,  116,  115,
      115,  120,  120,  123,  123,  207,  247,  128,  204,  130,
       87,   87,   87,  101,  101,  110,  110,  246,  129,  245,
      131,  131,  131,  187,  129,  135,  132,   87,  117,  117,
      188,  121,  129,  124,  132,  129,  136,  136,  120,  120,
      143,  155,  136,  102,  144,  111,  123,  123,  143,  158,
      136,  145,  144,  136,  128,  129,  244,  224,  118,  145,

      197,  129,  236,  236,  228,  129,  135,  197,  121,  129,
      242,  129,  129,  130,  236,  236,  124,  136,  136,  129,
      236,  236,  129,  136,  131,  131,  131,  160,  160,  160,
      132,  136,  248,  248,  136,  136,  136,  241,  132,  248,
      248,  136,  248,  248,  160,  160,  160,  160,  239,  136,
      253,  253,  136,  252,  252,  238,  237,  235,  234,  233,
      232,  231,  160,  240,  240,  240,  230,  240,  240,  240,
      243,  240,  240,  240,  240,  240,  243,  243,  243,  240,
      240,  240,  240,  243,  243,  243,  243,  243,  243,  243,
      243,  240,  240,  243,  240,  243,  243,  243,  243,  243,

      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      240,  240,  252,  253,  253,  229,  252,  252,  252,  254,
      252,  252,  252,  252,  252,  254,  254,  254,  252,  252,
      252,  252,  254,  254,  254,  254,  254,  254,  254,  254,
      252,  252,  254,  252,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  252,
      252,  257,  257,  257,  227,  257,  257,  257,  258,  257,
      257,  257,  257,  257,  258,  258,  258,  257,  257,  257,
      257,  258,  258,  258,  258,  258,  258,  258,  258,  257,
      257,  258,  257,  258,  258,  258,  258,  258,  258,  258,

      258,  258,  258,  258,  258,  258,  258,  258,  257,  257,
       49,   49,   49,   49,   49,   49,   49,   52,   52,   52,
       52,   52,   52,   52,   54,   54,   54,   54,   54,   54,
       54,   58,   58,   58,   58,   58,   58,   58,   59,   59,
       59,   59,   59,   59,   59,   77,   77,   77,   77,   94,
       94,   94,   94,   96,   96,  114,  114,  114,  114,  115,
      115,  226,  115,  115,  115,  115,  126,  126,  126,  126,
      134,  225,  223,  134,  134,  142,  142,  142,  142,  240,
      240,  222,  240,  240,  240,  240,  252,  252,  221,  252,
      252,  252,  252,  257,  257,  220,  257,  257,  257,  257,

      219,  218,  217,  216,  215,  214,  213,  212,  211,  210,
      209,  208,  206,  205,  202,  201,  197,  200,  199,  198,
      195,  194,  193,  192,  191,  190,  189,  186,  185,  184,
      161,  183,  181,  180,  177,  174,  173,  172,  171,  170,
      167,  166,  165,  164,  163,  162,  259,  133,  161,  153,
      150,  149,  146,  141,  140,  139,  133,  127,  125,  107,
       97,   95,   84,   78,   76,  259,   74,   60,   60,   53,
       53,   27,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,

      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259
    } ;

static yyconst short int yy_chk[822] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        2,    3,    4,    7,   57,    7,   20,   20,    3,    4,
        8,  255,    8,   12,   12,   12,   37,  112,   37,  112,
       38,   38,   38,   39,   39,   40,   40,   57,    7,    2,
       41,   41,  119,  147,  119,    8,   20,   38,   62,   69,
      147,   62,   69,   12,   13,   13,   13,   13,   13,   13,

       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   18,   18,   18,   22,   22,   24,   24,   24,

       46,   48,  122,  250,  122,   48,   47,   47,   86,   71,
       71,   48,   48,   71,  125,  244,  125,   86,  104,   71,
       71,   46,   18,  104,  155,   22,  155,   24,   25,   25,
       25,   25,   25,   25,   25,   25,   47,  239,   25,   46,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   35,   35,  153,   35,   35,
       35,   61,   61,  102,  153,   68,   68,  102,   35,   83,
       83,   35,   83,   83,  102,  111,   35,   35,  111,  158,
      118,  158,   83,  118,  173,   83,  180,  173,  238,  180,
       83,   61,   67,   67,   67,   68,   67,   67,   67,   67,

       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   70,   70,   72,   72,  183,  233,   79,  183,   80,
       87,   87,   87,  101,  101,  110,  110,  231,   79,  230,
       80,   80,   80,  165,   79,   82,   80,   87,  117,  117,
      165,   70,   79,   72,   80,   79,   82,   82,  120,  120,
      121,  121,   82,  101,  121,  110,  123,  123,  124,  124,
       82,  121,  124,   82,  128,  129,  229,  201,  117,  124,

      201,  129,  215,  215,  206,  128,  135,  206,  120,  129,
      225,  128,  129,  130,  232,  232,  123,  135,  135,  128,
      236,  236,  128,  135,  130,  130,  130,  131,  131,  131,
      130,  135,  237,  237,  135,  136,  136,  223,  130,  247,
      247,  136,  248,  248,  131,  160,  160,  160,  218,  136,
      253,  253,  136,  254,  254,  217,  216,  214,  213,  212,
      211,  210,  160,  226,  226,  226,  209,  226,  226,  226,
      226,  226,  226,  226,  226,  226,  226,  226,  226,  226,
      226,  226,  226,  226,  226,  226,  226,  226,  226,  226,
      226,  226,  226,  226,  226,  226,  226,  226,  226,  226,

      226,  226,  226,  226,  226,  226,  226,  226,  226,  226,
      226,  226,  249,  249,  249,  208,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  249,  249,
      249,  256,  256,  256,  205,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,

      256,  256,  256,  256,  256,  256,  256,  256,  256,  256,
      260,  260,  260,  260,  260,  260,  260,  261,  261,  261,
      261,  261,  261,  261,  262,  262,  262,  262,  262,  262,
      262,  263,  263,  263,  263,  263,  263,  263,  264,  264,
      264,  264,  264,  264,  264,  265,  265,  265,  265,  266,
      266,  266,  266,  267,  267,  268,  268,  268,  268,  269,
      269,  204,  269,  269,  269,  269,  270,  270,  270,  270,
      271,  202,  200,  271,  271,  272,  272,  272,  272,  273,
      273,  199,  273,  273,  273,  273,  274,  274,  198,  274,
      274,  274,  274,  275,  275,  197,  275,  275,  275,  275,

      195,  194,  193,  192,  191,  190,  189,  188,  187,  186,
      185,  184,  182,  181,  179,  178,  177,  176,  175,  174,
      172,  171,  170,  169,  168,  167,  166,  164,  163,  162,
      161,  159,  157,  156,  154,  152,  151,  150,  149,  148,
      146,  145,  144,  143,  138,  137,  134,  133,  132,  113,
      106,  105,  103,   93,   90,   88,   81,   76,   73,   51,
       45,   43,   36,   34,   30,   27,   23,   17,   11,    6,
        5,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,

      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() (yy_more_flag = 1)
#define YY_MORE_ADJ yy_more_len
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 ".\\verilog.l"
#define INITIAL 0
#line 2 ".\\verilog.l"
#include <stdio.h>
#include <errno.h>
#include <string>
#include <vector>
#include "public.h"
#include "parse_misc.h"
#include "FileParse.h"
#include "verilog.tab.hpp"
using namespace std;

int file_num;
int file_num_max;
static int line_num=1;
static int column=1;
static int pos=0;
char **files;
FileParse * my_parse=NULL;
static int state_stack[20];
static int state_sp=0;
static int ifdel_deep=0;
extern int errno;
static int lookup_key_word(char * yytext, int begin_pos, int yyleng);
#define RECORD_YYLLOC  do { 			\
        yylloc.first_line = line_num;   \
        yylloc.first_column = column;   \
        yylloc.begin_pos = pos;         \
        column+=yyleng;                 \
        pos+=yyleng;                    \
        yylloc.last_line = line_num;    \
        yylloc.last_column = column;    \
        yylloc.end_pos = pos;           \
        ASSERT(my_parse->get_text(yylloc.begin_pos, yylloc.end_pos)==yytext); \
    } while(0)

#define PUSH_STATE state_stack[state_sp++] = YY_START
#define POP_STATE BEGIN(state_stack[--state_sp])
#define CCOMMENT 1

#define LCOMMENT 2

#define CSTRING 3

#define PPTIMESCALE 4

#define IFDEF_DEL 5

#define IFDEF_JUDGE 6

#define IFNDEF_JUDGE 7

#define ELSE_DEL 8

#define IFDEF_ACCEPT 9

#define ELSE_ACCEPT 10

#define DEFINE 11

#define STATE_NAME 12

#line 697 "lex.yy.cpp"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 52 ".\\verilog.l"

#line 853 "lex.yy.cpp"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_more_len = 0;
		if ( yy_more_flag )
			{
			yy_more_len = yy_c_buf_p - yytext_ptr;
			yy_more_flag = 0;
			}
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 260 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 772 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 53 ".\\verilog.l"
{ column+=yyleng; pos+=yyleng; PUSH_STATE; BEGIN(STATE_NAME); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 54 ".\\verilog.l"
{
							RECORD_YYLLOC; 
							BEGIN(LCOMMENT); 
							yylval.emt = my_parse->element_new(pos-yyleng, pos, line_num,  Element::ELEMENT_NORMAL, 0);
							return STATENAME; 
						}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 60 ".\\verilog.l"
{RECORD_YYLLOC; PUSH_STATE; BEGIN(LCOMMENT); return K_dowhile; }						
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 61 ".\\verilog.l"
{ column+=yyleng; pos+=yyleng; PUSH_STATE; BEGIN(LCOMMENT); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 62 ".\\verilog.l"
{ column+=yyleng; pos+=yyleng;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 63 ".\\verilog.l"
{ column=1; line_num++; pos+=1; POP_STATE; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 64 ".\\verilog.l"
{ column+=yyleng; pos+=yyleng; PUSH_STATE; BEGIN(CCOMMENT); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 65 ".\\verilog.l"
{ column+=yyleng; pos+=yyleng;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 66 ".\\verilog.l"
{ column=1; line_num++; pos+=1;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 67 ".\\verilog.l"
{ column+=yyleng; pos+=yyleng; POP_STATE;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 68 ".\\verilog.l"
{ column+=yyleng; pos+=yyleng; PUSH_STATE; BEGIN(CSTRING); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 69 ".\\verilog.l"
{ column+=yyleng; pos+=yyleng; yymore(); /* Catch \\, which is a \ escaping itself */ }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 70 ".\\verilog.l"
{ column+=yyleng; pos+=yyleng; yymore(); /* Catch \", which is an escaped quote */ }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 71 ".\\verilog.l"
{ column=1; line_num++; pos+=1; POP_STATE; printf("Missing close quote of string at line %d", line_num); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 72 ".\\verilog.l"
{ RECORD_YYLLOC;  POP_STATE;  return STRING;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 73 ".\\verilog.l"
{ column+=yyleng; pos+=yyleng; yymore(); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 74 ".\\verilog.l"
{ RECORD_YYLLOC;  PUSH_STATE; BEGIN(DEFINE); return K_define; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 75 ".\\verilog.l"
{ RECORD_YYLLOC;  PUSH_STATE; BEGIN(DEFINE); return K_undef; }       
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 76 ".\\verilog.l"
{ yylloc.first_line = line_num;
                          yylloc.first_column = column;
                          yylloc.last_line = line_num;
                          yylloc.last_column = column+1;
                          yylloc.begin_pos = pos;
                          yylloc.end_pos = pos;
                          column=1; 
                          line_num++; 
                          pos+=1;
                          POP_STATE;                       
                          return K_enddefine; }                          
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 87 ".\\verilog.l"
{ column+=yyleng; pos+=yyleng; PUSH_STATE; BEGIN(IFDEF_JUDGE); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 88 ".\\verilog.l"
{ column+=yyleng; pos+=yyleng; PUSH_STATE; BEGIN(IFNDEF_JUDGE); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 89 ".\\verilog.l"
{ column+=yyleng; pos+=yyleng;
                                          if (my_parse->lookup_define(yytext))
                                              BEGIN(IFDEF_ACCEPT);
                                          else
                                              BEGIN(IFDEF_DEL);
                                        }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 95 ".\\verilog.l"
{ printf("ifdef empty followed at line %d", line_num); exit(1); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 96 ".\\verilog.l"
{ column+=yyleng; pos+=yyleng;
                                          if (!my_parse->lookup_define(yytext))
                                              BEGIN(IFDEF_ACCEPT);
                                          else
                                              BEGIN(IFDEF_DEL);
                                        }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 102 ".\\verilog.l"
{ printf("ifndef no valid identifier followed at line %d", line_num); exit(1); }                                        
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 103 ".\\verilog.l"
{ printf("ifndef empty followed at line %d", line_num); exit(1); }                              
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 104 ".\\verilog.l"
{ column=1; line_num++; pos+=1; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 105 ".\\verilog.l"
{ column+=yyleng; pos+=yyleng; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 106 ".\\verilog.l"
{ column+=yyleng; pos+=yyleng; ifdel_deep++; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 107 ".\\verilog.l"
{ column+=yyleng; pos+=yyleng; ifdel_deep++; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 108 ".\\verilog.l"
{ column+=yyleng; pos+=yyleng; 
                          if (ifdel_deep==0)
                              BEGIN(ELSE_ACCEPT);
                        }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 112 ".\\verilog.l"
{ 
                          column+=yyleng; pos+=yyleng;
                          if (ifdel_deep==0)
                              POP_STATE;
                          else
                              ifdel_deep--;
                        }               
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 119 ".\\verilog.l"
{ column+=yyleng; pos+=yyleng; BEGIN(ELSE_DEL); } 
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 120 ".\\verilog.l"
{ printf("`else is more than twice at line %d", line_num); exit(1); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 121 ".\\verilog.l"
{ printf("not support elsif at line %d", line_num); exit(1); }       
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 122 ".\\verilog.l"
{ column+=yyleng; pos+=yyleng; POP_STATE; }     
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 123 ".\\verilog.l"
{ RECORD_YYLLOC; return K_include;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 124 ".\\verilog.l"
{ RECORD_YYLLOC; return K_include; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 125 ".\\verilog.l"
{ RECORD_YYLLOC; return lookup_key_word(yytext, pos-yyleng, yyleng); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 126 ".\\verilog.l"
{ RECORD_YYLLOC; return SYSTEM_IDENTIFIER; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 127 ".\\verilog.l"
{ RECORD_YYLLOC; return DEFINE_IDENTIFIER; }                       
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 128 ".\\verilog.l"
{ column =1; line_num++; pos+=1; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 129 ".\\verilog.l"
{ RECORD_YYLLOC; return K_LS; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 130 ".\\verilog.l"
{ RECORD_YYLLOC; return K_LS; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 131 ".\\verilog.l"
{ RECORD_YYLLOC; return K_RS; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 132 ".\\verilog.l"
{ RECORD_YYLLOC; return K_RSS; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 133 ".\\verilog.l"
{ RECORD_YYLLOC; return K_LE; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 134 ".\\verilog.l"
{ RECORD_YYLLOC; return K_GE; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 135 ".\\verilog.l"
{ RECORD_YYLLOC; return K_EG; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 136 ".\\verilog.l"
{ RECORD_YYLLOC; return K_EQ; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 137 ".\\verilog.l"
{ RECORD_YYLLOC; return K_NE; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 138 ".\\verilog.l"
{ RECORD_YYLLOC; return K_CEQ; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 139 ".\\verilog.l"
{ RECORD_YYLLOC; return K_CNE; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 140 ".\\verilog.l"
{ RECORD_YYLLOC; return K_LOR; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 141 ".\\verilog.l"
{ RECORD_YYLLOC; return K_LAND; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 142 ".\\verilog.l"
{ RECORD_YYLLOC; return K_NOR; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 143 ".\\verilog.l"
{ RECORD_YYLLOC; return K_NXOR; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 144 ".\\verilog.l"
{ RECORD_YYLLOC; return K_NXOR; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 145 ".\\verilog.l"
{ RECORD_YYLLOC; return K_NAND; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 146 ".\\verilog.l"
{ RECORD_YYLLOC; return K_TRIGGER; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 147 ".\\verilog.l"
{ RECORD_YYLLOC; return *yytext; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 148 ".\\verilog.l"
{ RECORD_YYLLOC; return BASED_NUMBER; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 149 ".\\verilog.l"
{ RECORD_YYLLOC; return BASED_NUMBER; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 150 ".\\verilog.l"
{ RECORD_YYLLOC; return BASED_NUMBER; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 151 ".\\verilog.l"
{ RECORD_YYLLOC; return BASED_NUMBER; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 152 ".\\verilog.l"
{ RECORD_YYLLOC; return BASED_NUMBER; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 153 ".\\verilog.l"
{ RECORD_YYLLOC;  return DEC_NUMBER; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 154 ".\\verilog.l"
{ column+=yyleng; pos+=yyleng; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 155 ".\\verilog.l"
ECHO;
	YY_BREAK
#line 1322 "lex.yy.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(CCOMMENT):
case YY_STATE_EOF(LCOMMENT):
case YY_STATE_EOF(CSTRING):
case YY_STATE_EOF(PPTIMESCALE):
case YY_STATE_EOF(IFDEF_DEL):
case YY_STATE_EOF(IFDEF_JUDGE):
case YY_STATE_EOF(IFNDEF_JUDGE):
case YY_STATE_EOF(ELSE_DEL):
case YY_STATE_EOF(IFDEF_ACCEPT):
case YY_STATE_EOF(ELSE_ACCEPT):
case YY_STATE_EOF(DEFINE):
case YY_STATE_EOF(STATE_NAME):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 260 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 260 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 259);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 155 ".\\verilog.l"

static int lookup_key_word(char * yytext, int begin_pos, int yyleng)
{       
        if (strcmp(yytext, "always")==0)
                return K_always;
        if (strcmp(yytext, "assign")==0)
                return K_assign;
        if (strcmp(yytext, "automatic")==0)
                return K_automatic;
        if (strcmp(yytext, "begin")==0)
                return K_begin;
        if (strcmp(yytext, "case")==0)
                return K_case;
        if (strcmp(yytext, "casex")==0)
                return K_casex;
        if (strcmp(yytext, "casez")==0)
                return K_casez;
        if (strcmp(yytext, "deassign")==0)
                return K_deassign;
        if (strcmp(yytext, "default")==0)
                return K_default;
        if (strcmp(yytext, "defparam")==0)
                return K_defparam;
        if (strcmp(yytext, "disable")==0)
                return K_disable;
        if (strcmp(yytext, "else")==0)
                return K_else;
        if (strcmp(yytext, "end")==0)
                return K_end;
        if (strcmp(yytext, "endcase")==0)
                return K_endcase;
        if (strcmp(yytext, "endfunction")==0)
                return K_endfunction;
        if (strcmp(yytext, "endgenerate")==0)
                return K_endgenerate;   
        if (strcmp(yytext, "endmodule")==0)
                return K_endmodule;
        if (strcmp(yytext, "endspecify")==0)
                return K_endspecify;    
        if (strcmp(yytext, "endtask")==0)
                return K_endtask;
        if (strcmp(yytext, "event")==0)
                return K_event;
        if (strcmp(yytext, "for")==0)
                return K_for;
        if (strcmp(yytext, "force")==0)
                return K_force;
        if (strcmp(yytext, "forever")==0)
                return K_forever;
        if (strcmp(yytext, "fork")==0)
                return K_fork;
        if (strcmp(yytext, "function")==0)
                return K_function;
        if (strcmp(yytext, "generate")==0)
                return K_generate;
        if (strcmp(yytext, "genvar")==0)
                return K_genvar;
        if (strcmp(yytext, "if")==0)
                return K_if;
        if (strcmp(yytext, "initial")==0)
                return K_initial;
        if (strcmp(yytext, "inout")==0)
                return K_inout;
        if (strcmp(yytext, "input")==0)
                return K_input;
        if (strcmp(yytext, "integer")==0)
                return K_integer;       
        if (strcmp(yytext, "join")==0)
                return K_join;
        if (strcmp(yytext, "localparam")==0)
                return K_localparam;    
        if (strcmp(yytext, "macromodule")==0)
                return K_macromodule;
        if (strcmp(yytext, "module")==0)
                return K_module;
        if (strcmp(yytext, "negedge")==0)
                return K_negedge;
        if (strcmp(yytext, "or")==0)
                return K_or;
        if (strcmp(yytext, "output")==0)
                return K_output;
        if (strcmp(yytext, "parameter")==0)
                return K_parameter;
        if (strcmp(yytext, "posedge")==0)
                return K_posedge;
        if (strcmp(yytext, "reg")==0)
                return K_reg;
        if (strcmp(yytext, "release")==0)
                return K_release;
        if (strcmp(yytext, "repeat")==0)
                return K_repeat;
        if (strcmp(yytext, "signed")==0)
                return K_signed;
        if (strcmp(yytext, "specify")==0)
                return K_specify;               
        if (strcmp(yytext, "task")==0)
                return K_task;
        if (strcmp(yytext, "unsigned")==0)
                return K_unsigned;      
        if (strcmp(yytext, "wait")==0)
                return K_wait;
        if (strcmp(yytext, "while")==0)
                return K_while; 
        if (strcmp(yytext, "wire")==0)
                return K_wire;        
        yylval.emt = my_parse->element_new(begin_pos, begin_pos+yyleng, line_num, Element::ELEMENT_NORMAL, 0);
        if (strcmp(yytext, "ASYNC_RESET")==0)
        		return K_ASYNC_RESET;
        return IDENTIFIER;
}
int prepare(int argc, char *argv[]) {
        file_num=1;
        file_num_max = argc;
        files = argv;
        my_parse = new FileParse;           
        if ( argc > 1 ) {                
                my_parse->load_file(argv[file_num]);
                if ( (yyin = fopen(argv[file_num],"r")) == 0 ) {
                        perror(argv[file_num]);
                        exit(1);
                }
        } else {
                my_parse->load_file(".\\test\\t0.v");
                if ( (yyin = fopen(".\\test\\t0.v","r")) == 0 ) {
                        perror(argv[file_num]);
                        exit(1);
                }
        }    
        return 0;
}

int yywrap() {
        fclose(yyin);
        if (ifdel_deep>0) {
            printf("if endif mismatch");
            exit(1);
        }
        if ( ++file_num < file_num_max ) {
                delete my_parse;
                my_parse = new FileParse;
                my_parse->load_file(files[file_num]);
                if ( (yyin = fopen(files[file_num],"r")) == 0 ) {
                        perror(files[file_num]);
                        exit(1);
                }
                return 0;
        } else {
                return 1;
        }
}
